import type { ExportBundle, RecordedEvent, RecordingTimeline } from '../types/index.js';

const INTERACTION_CATEGORIES = new Set<RecordedEvent['category']>([
  'navigation',
  'mouse',
  'keyboard',
  'form',
  'selection',
  'drag-and-drop',
  'scroll',
  'window',
  'action'
]);

function byCategory(
  events: readonly RecordedEvent[],
  category: RecordedEvent['category']
) {
  return events.filter((event) => event.category === category);
}

function describeEvent(event: RecordedEvent): string {
  const detail = event.detail as Record<string, unknown>;
  switch (event.category) {
    case 'navigation':
      return `navigated (${detail.kind}) to ${detail.url}`;
    case 'mouse':
      return `${detail.kind} on ${(detail.target as { selector: string }).selector}`;
    case 'keyboard':
      return `${detail.kind} "${detail.key}"${detail.isShortcut ? ' (shortcut)' : ''}`;
    case 'form':
      return `field "${detail.fieldName}" changed (length ${detail.valueLength}, ${detail.validationResult})`;
    case 'selection':
      return `${detail.kind} selection on ${(detail.target as { selector: string }).selector}`;
    case 'drag-and-drop':
      return `dragged ${(detail.source as { selector: string }).selector} → ${
        (detail.destination as { selector: string } | null)?.selector ?? '(none)'
      }`;
    case 'scroll':
      return `scrolled ${detail.direction} on ${(detail.container as { selector: string }).selector}`;
    case 'window':
      return `window ${detail.kind}`;
    case 'action':
      return `action "${detail.name}"`;
    case 'console':
      return `console.${detail.severity}: ${(detail.arguments as string[]).join(' ')}`;
    case 'network':
      return `${detail.method} ${detail.url} → ${detail.status ?? 'failed'} (${detail.durationMs}ms)`;
    case 'runtime':
      return `${detail.kind}: ${detail.message}`;
  }
}

function screenshotLink(event: RecordedEvent): string {
  return event.screenshot
    ? ` ([screenshot](./screenshots/event-${event.sequence}.png))`
    : '';
}

function buildTimelineSection(events: readonly RecordedEvent[]): string {
  if (!events.length) return '_No events recorded._';
  return events
    .map(
      (event) =>
        `- \`#${event.sequence}\` [+${event.elapsedMs}ms] ${describeEvent(event)}${screenshotLink(event)}`
    )
    .join('\n');
}

function buildErrorsSection(events: readonly RecordedEvent[]): string {
  const runtimeEvents = byCategory(events, 'runtime');
  if (!runtimeEvents.length) return '_No runtime errors._';
  return runtimeEvents
    .map((event) => {
      const detail = event.detail as Record<string, unknown>;
      const cause =
        detail.triggeredBySequence != null
          ? ` (triggered by action #${detail.triggeredBySequence})`
          : '';
      return `- \`#${event.sequence}\` **${detail.kind}**: ${detail.message}${cause}${screenshotLink(event)}`;
    })
    .join('\n');
}

function buildNetworkFailuresSection(events: readonly RecordedEvent[]): string {
  const failures = byCategory(events, 'network').filter(
    (event) => (event.detail as Record<string, unknown>).failed
  );
  if (!failures.length) return '_No failed requests._';
  return failures
    .map((event) => {
      const detail = event.detail as Record<string, unknown>;
      return `- \`#${event.sequence}\` ${detail.method} ${detail.url} → ${detail.status ?? 'network error'}`;
    })
    .join('\n');
}

function buildMarkdownReport(timeline: RecordingTimeline): string {
  const { events, environment, metadata } = timeline;
  return `# Browser Debug Session Report

## Environment

- URL: ${environment.url}
- User agent: ${environment.userAgent}
- Viewport: ${environment.viewport.width}×${environment.viewport.height}
- Recorded at: ${environment.recordedAt}

## Session

- Started: ${metadata.startedAt}
- Stopped: ${metadata.stoppedAt ?? '(not stopped)'}
- Duration: ${metadata.durationMs}ms
- Total events: ${metadata.eventCount}

## Executed Actions

${buildTimelineSection(events.filter((event) => INTERACTION_CATEGORIES.has(event.category)))}

## Errors

${buildErrorsSection(events)}

## Network Failures

${buildNetworkFailuresSection(events)}

## Final Application State

${(() => {
  const last = [...events]
    .reverse()
    .find((event) => event.category === 'navigation' || event.category === 'action');
  return last
    ? describeEvent(last)
    : '_Unknown — no navigation or action events recorded._';
})()}

---

_Generated by the Browser Debug Recorder. Attach this file, or the full \`browser-debug-session/\` folder, directly to an AI conversation for reproduction._
`;
}

/**
 * Pure transform from a recording into the exportable file set described in
 * IMPLEMENT_BROWSER_DEBUG_RECORDER.md's "Export Format". A screenshot exists
 * only for events in `SCREENSHOT_CATEGORIES` (navigation/runtime/action) that
 * finished capturing before export — see that section for why not every
 * event gets one.
 */
export function buildExport(timeline: RecordingTimeline): ExportBundle {
  const { events } = timeline;

  const files: Record<string, string> = {
    'report.md': buildMarkdownReport(timeline),
    'session.json': JSON.stringify(timeline, null, 2),
    'actions.json': JSON.stringify(
      events.filter((event) => INTERACTION_CATEGORIES.has(event.category)),
      null,
      2
    ),
    'console.json': JSON.stringify(byCategory(events, 'console'), null, 2),
    'network.json': JSON.stringify(byCategory(events, 'network'), null, 2),
    'runtime.json': JSON.stringify(byCategory(events, 'runtime'), null, 2),
    'environment.json': JSON.stringify(timeline.environment, null, 2),
    'metadata.json': JSON.stringify(timeline.metadata, null, 2)
  };

  const binaryFiles: Record<string, string> = {};
  const withScreenshot = events.filter((event) => event.screenshot);
  for (const event of withScreenshot)
    binaryFiles[`screenshots/event-${event.sequence}.png`] = event.screenshot!;

  if (!withScreenshot.length)
    files['screenshots/README.md'] =
      'No screenshots were captured for this session — either none of the ' +
      'recorded events were in a screenshot category (navigation/runtime/action), ' +
      'or capture failed for all of them.\n';

  return { files, binaryFiles };
}
